### ISSUE TITLE
gen.gen_c: a set reaching a wider STRUCTURAL set at a tail is unclaimed in expression position -- sema accepts, cc rejects (needs write_retag's map where only an expression fits)

### ISSUE THREAD

**Issue by lantos1618** [lantos1618/zen-holotype#842]
Sibling of #828 (fixed): the DECLARED-destination face now tags the whole arriving set through `carrier`/`wrap_error`, because the destination unions the arriving SET itself. This is the other face: the destination composes its members INLINE, so no variant names the arriving set and the arrival must be re-tagged member by member -- exactly what `.try()`'s `write_retag` switch does as a STATEMENT. A conversion in an expression buffer can hold no statement, so gen_c_widen deliberately leaves this pair unclaimed (see the NARROW ON PURPOSE header in src/gen/gen_c/gen_c_widen.zen).

## Repro

```zen
N1 = | Alpha
N2 = | Beta
Mid = N1 | N2
N3 = | Gamma

inner = (ok: bool) Res<u64, Mid> {
    ok.match({
        true  => Ok(7),
        false => Err(N1.Alpha),
    });
}

outer = (ok: bool) Res<u64, N1 | N2 | N3> {
    inner(ok);
}

main = (env: Env) Res<i32, AllocError> {
    r = outer(true);
    r.match({
        Ok(v)  => println("v={}", v),
        Err(_) => println("WRONG"),
    });
    Ok(0);
}
```

`zen build` exits 0; cc then refuses:

```
error: incompatible types when initializing type 'int' using type 'zu_t.._3Mid'
     return (zg_t1.zg_tag == ...Res2Ok ? (...) : (...{ ..., .zg_data.zu_m3Err = zg_t1.zg_data.zu_m3Err }));
```

## The wrong-value face any fix must not take

A byte copy compiles (same flattened layout) and LIES: the two sets number their own members independently, so Mid's tag 0 (`Alpha`) read under `N1 | N2 | N3`'s numbering is still tag 0 here by coincidence of order -- reorder the destination to `N3 | N1 | N2` and it reads as `Gamma`: exit 0, plausible output, no diagnostic. Any fix must map tags member by member like `write_retag`, and the test must print WHICH member arrived under BOTH member orders.

## Why not fixed alongside #828

Claiming it at the widen door needs either an initializer form of the tag map or a hoist of the conversion into a statement -- a design decision, not a one-line repair. Today the failure is a loud cc refusal, not a silent wrong value.

**Comment by lantos1618** [comment]
Fixed on branch issue-842 (ecc0c2c8b, base 346e60267).

What is now true: a Res whose error slot carries a SET (a declared alias like Mid = N1 | N2, or an inline union) reaching a wider STRUCTURAL set in expression position -- a tail `return callee(..)`, an argument, an initialiser -- lowers through gen_c_try.retag_set: the value spills into a temporary at its own type, the payload crosses at the source's size, and the tag is remapped member by member through write_member_tag constants named at each side's written spelling. gen_c_bound.convert_kind asks set_of(dst) before dispatching, so an alias destination no longer falls through to convert_named's bare copy; gen_c_widen.member_reaches_set claims the set-to-set pair at the widen door via be.set_retags. Both spellings resolve through set_of first (#736's law), and containment is sema's own set_within.

Proof (both halves measured):
- RED on the pre-draft base (346e60267 compiler rebuilt in isolation): the issue's own repro fails cc with "incompatible types when returning" -- the exact refusal from this issue.
- GREEN on HEAD: same repro compiles, runs, prints v=7.
- New corpus pin tests/corpus/errors-widen/set_reaching_wider_set_at_a_tail_is_retagged prints WHICH member arrived under both member orders ([N1,N2,N3] and [N3,N1,N2]); it fails on the base compiler and passes on HEAD.
- Filtered runs green on HEAD: errors-widen 6/6, codegen 50 passed / 1 deferred, must-fail 238 passed / 2 deferred, std 86/86, example suite unchanged.

**Comment by lantos1618** [comment]
Fixed on branch issue-842 (ecc0c2c8b, base 346e60267).

What is now true: a Res whose error slot carries a SET (a declared alias like Mid = N1 | N2, or an inline union) reaching a wider STRUCTURAL set in expression position -- a tail `return callee(..)`, an argument, an initialiser -- lowers through gen_c_try.retag_set: the value spills into a temporary at its own type, the payload crosses at the source's size, and the tag is remapped member by member through write_member_tag constants named at each side's written spelling. gen_c_bound.convert_kind asks set_of(dst) before dispatching, so an alias destination no longer falls through to convert_named's bare copy; gen_c_widen.member_reaches_set claims the set-to-set pair at the widen door via be.set_retags. Both spellings resolve through set_of first (#736's law), and containment is sema's own set_within.

Proof (both halves measured):
- RED on the pre-draft base (346e60267 compiler rebuilt in isolation): the issue's own repro fails cc with "incompatible types when returning" -- the exact refusal from this issue.
- GREEN on HEAD: same repro compiles, runs, prints v=7.
- New corpus pin tests/corpus/errors-widen/set_reaching_wider_set_at_a_tail_is_retagged prints WHICH member arrived under both member orders ([N1,N2,N3] and [N3,N1,N2]); it fails on the base compiler and passes on HEAD.
- Filtered runs green on HEAD: errors-widen 6/6, codegen 50 passed / 1 deferred, must-fail 238 passed / 2 deferred, std 86/86, example suite unchanged.
